### ISSUE TITLE
How did we clean the data

### ISSUE THREAD

**Issue by julia-redmoon** [Xiaohan-Alyssa-Zhang/CleverCogs-Group7#4]
We deleted all the data that is likely to be machine users according to Lynda, right? Anything else related to activities and medicals?

**Comment by MuyuDeng** [comment]
Yes, Lynda mentioned some outliers which could be regarded as machines rather than human beings, and I already filtered and removed all of them, such as users with unspecified gender or under 18 years of age. There are no outliers in the activities and every piece of data is valuable, but we need to classify it further.

**Comment by Xiaohan-Alyssa-Zhang** [comment]
In the medical conditions file, some external ids have been shown many times so we can delete some duplicate records. This is because one user probably has multiple Staffcare Conditions needs. Since we only focus on the CareSystemConditions rather than the StaffcareConditions, we can just use CareSystemCondition columns and ignore the duplicate records.

**Comment by JuneJuneJie** [comment]
1) Null data
Since the ExternalID in each table is the primary key that identifies the user to the connected tables, a null value does not meet the specification. We removed all data in the three tables where the ExternalID was null.
2) Negative data
For some data items with constant positive values, such as ExternalID and Age, we filtered and deleted the parts that are less than or equal to zero in three tables.
3) Data types
For users’ age, we know from the platform data specifications that CleverCogs is only for adults over the age of 18. Therefore we removed all data on minors. For users’ gender, we noticed that it is divided into three categories, female, male, and unspecified. We were unsure during the data processing whether unspecified gender referred to the non-binary or users preferred not to say. We assume that these users with unspecified gender are all machines rather than human beings. As you know, the gender category is an important factor when analyzing activities and medical conditions. To ensure the accuracy of the data analysis results, we have removed user information that does not identify a defined gender. The same applies to users who lack a date of birth.
